Init
Teaching-projects/SZE-MOSZE-2020-GitCraft pull request #1
Opened 2020-09-11 20:47 UTC by Patorik

2020-09-16 09:55 UTC, Patorik commented
@hegyhati  , módosítottam a programon úgy, hogy parancssorból lehessen a szoftvernek megadni az adatokat, valamint töröltük a Game classt is, mert egyelőre mégis feleslegesnek tartjuk.

2020-09-16 23:02 UTC, hegyhati commented
Ezt most review nelkul magatoktol? Vagy volt review @wajzy kollegatol? En ennek nem latom a nyomat.

2020-09-17 05:44 UTC, Patorik commented
@hegyhati , igen, review nélkül csináltuk, mert ránéztem még egyszer a kimenetre és akkor esett le, hogy parancssorból várjuk az adatok gyűjtését. A többi változtatás csak "kozmetkai" jellegű.

2020-09-19 10:30 UTC, Patorik commented
@hegyhati , @wajzy , elnézést, senkit nem szeretnénk sürgetni, de az egyik üzenetben az állt, hogy ha 3 napja nem kaptunk review-et, akkor azt jelezhetjük nyugodtan.

2020-09-19 15:42 UTC, wajzy requested changes
Ezt a pár apróságot javítsátok ki legyetek szívesek, nagy vonalakban jó a megoldás.

2020-09-19 15:42 UTC, wajzy commented on README.md
> +* A **print()** függvény kiírja a karakter tulajdonságait a mintában megadott módon.
Én inkább a << operátor felültöltését javaslom.

2020-09-19 15:42 UTC, wajzy commented on character.cpp
> +}
Ezt javaslom törölni, nincs így sok haszna.

2020-09-19 15:42 UTC, wajzy commented on character.cpp
> +bool Character::isAlive()
Ez is legyen const, nem kell változtatnia semmin.

2020-09-19 15:42 UTC, wajzy commented on character.cpp
> +void Character::print()
Ez is lehetne const, de ha tényleg lesz operátor felültöltés, akkor ez lehet, hogy tárgytalan.

2020-09-19 17:59 UTC, Patorik commented
@wajzy köszönjük szépen, a kért módosításokat megcsináltuk.

2020-09-21 08:39 UTC, wajzy approved these changes
@hegyhati @Patorik  OK, elfogadom a módosításokat.

2020-09-21 14:52 UTC, merged