Testing
Teaching-projects/SZE-MOSZE-2020-GitCraft pull request #2
Opened 2020-09-24 15:02 UTC by ztamas97

2020-09-24 16:33 UTC, hegyhati commented
PR description sose legyen empty. irtam.

2020-09-24 16:40 UTC, hegyhati requested changes
Par aprosag.

2020-09-24 16:40 UTC, hegyhati commented on .github/workflows/main.yml
> +      - run: chmod +x test.sh
ezt eleg lenne egyszer lokalisan

2020-09-24 16:40 UTC, hegyhati commented on character.cpp
> +			if (line.find(s) != std::string::npos) {
hasznalod meg barhol mashol az s-t? ha nem, akkor nem lett volna egyszerubb egy sorban?

2020-09-24 16:40 UTC, hegyhati commented on character.cpp
> +			if (line.find(s) != std::string::npos) {
Sot, az a ket if is mehet egyetlen sorba, es akkor meg atlathatobb a kod.

2020-09-24 16:40 UTC, hegyhati commented on character.h
> +	static Character parseUnit(std::string charSheetName);
indentalas kicsit offnak tunik

2020-09-24 16:40 UTC, hegyhati commented on main.cpp
>  	}
ilyen esetekben ne engedjuk, hogy a return 0-ig eljusson. Igenis adjon hibakodot a program.

2020-09-24 19:25 UTC, ztamas97 commented
@hegyhati , kijavítottuk a hibákat

2020-09-25 13:48 UTC, hegyhati approved these changes

2020-09-25 13:49 UTC, merged