Levelup
Teaching-projects/SZE-MOSZE-2020-GitCraft pull request #4
Opened 2020-10-13 18:42 UTC by ztamas97

A feladat végrehajtása során megvalósítottam egy fight metódust, ami egy Character objektum megtámadását teszi lehetővé, valamint a szintlépést.  Az attack segítségével történik meg a sebzések bevitele, valamint az Xp növelése is ennek a metódusnak a segítségével történik meg. A levelup teszi levetővé a szintlépést valamint az adatok módosítását új értékekre. Az ellenőrzés GHA- val történik meg. Tesztek során történik memória szemetelés ellenőrzése, statikus kód analízis, valamint in-out tesztek lefuttatása.

2020-10-14 11:28 UTC, oliverosz requested changes
A kerekítést leszámítva inkább csak stilisztikai hibák, amúgy rendben van a megoldás. Ezeket még javítsd ki.
@hegyhati közben kérek jogosultságot a merge-hez

2020-10-14 11:28 UTC, oliverosz commented on .github/workflows/main.yml
> +name: Levelup workflow
Ez nem levelup workflow. Nem csak a mostani feladatnál fog lefutni, hanem a későbbiekben is. De mindegy, maradhat.

2020-10-14 11:28 UTC, oliverosz commented on character.h
> +	void levelup();
Amit nem az osztály használójának kell hívnia, az ne legyen publikus.

2020-10-14 11:28 UTC, oliverosz commented on character.cpp
> +			C.health = std::stoi(line.substr(start + 2, length));
`C.health = C.maxHp;`

2020-10-14 11:28 UTC, oliverosz commented on character.cpp
> +		maxHp += floor(maxHp*0.1);
Kerekítés szerepelt a feladatleírásban, nem egész rész.

2020-10-14 11:28 UTC, oliverosz commented on character.cpp
> +		player.health = player.getHp() - this->getDmg();
`player.health -= getDmg();`
Sok itt a felesleges `this->`

2020-10-14 15:59 UTC, ztamas97 commented
@oliverosz , kijavítottam a hibákat

2020-10-15 13:36 UTC, oliverosz approved these changes
Ok, így már rendben van. Be is mergelem majd, amint megkapom a jogosultságot.

2020-10-15 13:40 UTC, hegyhati commented
> Ok, így már rendben van. Be is mergelem majd, amint megkapom a jogosultságot.

done.

2020-10-15 14:41 UTC, merged